//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElevesObjectifs
    {
        public int Id { get; set; }
        public Nullable<int> Niveaux { get; set; }
        public Nullable<int> IdObjectifs { get; set; }
        public Nullable<int> IdEleves { get; set; }
        public string Evaluation { get; set; }
    
        public virtual Eleves Eleves { get; set; }
        public virtual Objectifs Objectifs { get; set; }
    }
}
