//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branches> Branches { get; set; }
        public virtual DbSet<Classes> Classes { get; set; }
        public virtual DbSet<Eleves> Eleves { get; set; }
        public virtual DbSet<ElevesObjectifs> ElevesObjectifs { get; set; }
        public virtual DbSet<Objectifs> Objectifs { get; set; }
        public virtual DbSet<Professeurs> Professeurs { get; set; }
        public virtual DbSet<ProfesseursClasses> ProfesseursClasses { get; set; }
    }
}
