//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objectifs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Objectifs()
        {
            this.ElevesObjectifs = new HashSet<ElevesObjectifs>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public bool Minima { get; set; }
        public int IdGroupe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElevesObjectifs> ElevesObjectifs { get; set; }
        public virtual Groupes Groupes { get; set; }
    }
}
